### ISSUE TITLE
Annoying messages by Groovy log manager.

### ISSUE THREAD

**Issue by jhidding** [NLeSC/pyxenon#10] opened 2016-07-22 08:47 UTC
Groovy complains it finds 'conflicting logback.xml' files in its search path. Deleting the logback.xml from xenon/lib resolved this issue for me.

**Comment by blootsvoets** [comment] 2016-08-09 07:08
It's caused by the logback config, Xenon did not have it before so it complained about having none at all. Fixed in d323c222, by setting the logback file explicitly.

**Closed by blootsvoets** 2016-08-09 07:08 UTC
